name: Playwright Tests
 

trigger:
  - master
 

pool:
      vmImage: "windows-2019"
 

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18'
  displayName: 'ubuntu-latest'

- script: npm ci
  displayName: 'npm ci'

- script: npx playwright install --with-deps
  displayName: 'Install Playwright browsers'

- script: npm install --save-dev @cucumber/cucumber
  displayName: 'Install cucumber'

- script: npx tsc --init
  displayName: 'Install npx'

- script: chmod +x node_modules/.bin/cucumber-js
  displayName: 'Grant execute permission to cucumber-js'

- script: |
    npx cucumber-js --tags '@test'
  displayName: 'execute tests'