name: Playwright Tests
 

trigger:
  - main
 

pool:
      vmImage: "ubuntu-latest"
 
container: mcr.microsoft.com/playwright:v%version%-jammy

steps:

- script: |
    npm install
  displayName: 'npm install'

- script: chmod +x node_modules/.bin/cucumber-js
  displayName: 'Grant execute permission to cucumber-js'

- script: |
    npm run testTags -- --tags "@only" 
  displayName: 'execute tests'