pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18'
  displayName: 'Install Node.js'

- script: |
    npm ci
    npx playwright install --with-deps
    npm install @cucumber/cucumber -D
  displayName: 'Install dependencies'

- script: |
    npm run testTags --tags="@only"
  displayName: 'Run Playwright and Cucumber tests'