name: Playwright Tests
 

trigger:
  - main
 

pool:
      vmImage: "windows-2019"
 
container: mcr.microsoft.com/playwright:bionic

steps:

- script: |
    npm install
  displayName: 'npm install'


- script: |
    npm run testTags -- --tags "@only" 
  displayName: 'execute tests'