pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm install @cucumber/cucumber -D
    npm install -g playwright
  displayName: 'Install dependencies'

- script: |
    npm run testTags --tags="@only"
  displayName: 'Run Playwright and Cucumber tests'