name: Playwright Tests
 

trigger:
  - main
 

pool:
      vmImage: "ubuntu-latest"
 
container: mcr.microsoft.com/playwright:v1.28.0

steps:

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm i @cucumber/cucumber -D 
  displayName: 'instalar cucumber'

- script: |
    npx playwright test
  displayName: 'execute tests'